# Numpy

## Initializing a Numpy Array

In [1]:
import numpy as np

a = np.array([[1,4,3,7,8,10,13], [4,5,6,1,3,4,5], [2,5,6,3,5,6,8]], dtype='int16')

## Properties of numpy arrays

In [2]:
# Properties of array
def arrayInfo(a) :
  print(a)
  print('Array shape -', a.shape)
  print('Array dimensions -', a.ndim)
  print('Array Size giving total number of elements -', a.size)
  print('Array itemsize -', a.itemsize)
  print('Array Total Size -', a.size * a.itemsize)

In [3]:
arrayInfo(a)

[[ 1  4  3  7  8 10 13]
 [ 4  5  6  1  3  4  5]
 [ 2  5  6  3  5  6  8]]
Array shape - (3, 7)
Array dimensions - 2
Array Size giving total number of elements - 21
Array itemsize - 2
Array Total Size - 42


## Get Elements of Array

In [70]:
# Get Sepcific Element by index [r,c]
print(a[1,2]) # get element form 2nd row and 3 column

# using negative indexs starts count from the last index where -1 is the last index
print(a[2, -1])

# get specific row with all columns in that row
print(a[1, :])

# get specific columns from all rows
print(a[:, 3])

6
55
[ 4  5  6 88  3  4  5]
[14 88 88]


## Getting Element of Array using and start, end and steps

In [71]:
# Array Operations -> startindex:endindex:stepsize
# !! end index specified is not included, but start index element is included
# elements in 3rd column starting from 1st index till the -2 index, where -2 is not included
print(a[2, 1:-2:1])

[55 55 88 55]


## Editing Elements of Array

In [28]:
# Editing Array Elements

# Single Element at [r,c]
a[0,2] = 100
print(a[0, :])

# Change All elements in a row
a[2, :] = 55
print(a[2, :])

# Change all elements in a column
a[:, 3] = 88
print(a)

# Change element in a column giving specific value for each
a[0, :] = [10, 12, 13, 14, 15, 16, 17]
print(a[0, :])

[ 10  12 100  14  15  16  17]
[55 55 55 55 55 55 55]
[[ 10  12 100  88  15  16  17]
 [  4   5   6  88   3   4   5]
 [ 55  55  55  88  55  55  55]]
[10 12 13 14 15 16 17]


## Working with Higher Dimensional Arrays

In [121]:
b =np.array([[[1,3], [7,8]], [[4, 5], [3,9]]])
arrayInfo(b)
# [outermost, inner--->] index are to be given from outermost row to the column to be selected
# Edit Element
b[1, 0, 1] = 20
print(b)

# Edit all columns
b[:, :, 1] = 77
print(b)


[[[1 3]
  [7 8]]

 [[4 5]
  [3 9]]]
Array shape - (2, 2, 2)
Array dimensions - 3
Array Size giving total number of elements - 8
Array itemsize - 8
Array Total Size - 64
[[[ 1  3]
  [ 7  8]]

 [[ 4 20]
  [ 3  9]]]
[[[ 1 77]
  [ 7 77]]

 [[ 4 77]
  [ 3 77]]]


### Advanced Indexing

In [122]:
# Get Element from different column element from different rows
advancedIndex = b[[0, 1], [1, 0], [1, 0]] ## Specifies the index or rows and then columns to be selected
print(advancedIndex)

[77  4]


## Initializing Different types of template arrays

In [44]:
# Initializing Arrays

# Zeros array
zeros = np.zeros((2, 3, 3), dtype='int32')
print(zeros)
# The zeros array dimension can be increased by adding additional arguments

# Similarly a ones array
ones = np.ones((3, 3)) # no datatype is given
print(ones)

# Other number arrays
full = np.full((2, 2), 10, dtype='float32')
print(full)

# Full like another array
fulllike = np.full_like(a, 8, dtype='int32')
print(fulllike)
#else
fulllike2 = np.full(a.shape, 7, dtype='int16')
print(fulllike2)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[10. 10.]
 [10. 10.]]
[[8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8]]
[[7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]]


## Creating Arrays with Random Data

In [51]:
# Create Random Arrays
random = np.random.rand(3,4)
print(random)

# One random number
print(np.random.randint(10, 100))

# random array filled with values between
random2 = np.random.randint(-10, 20, size=(3,3), dtype='int32')
print(random2)

[[0.11213204 0.72491563 0.32823382 0.90101588]
 [0.76955072 0.31608607 0.58168619 0.34667779]
 [0.7565188  0.83853658 0.80923206 0.82176487]]
37
[[-6 16 11]
 [15 -9  4]
 [ 8 16 18]]


## Repeating Array to create new Arrays

In [56]:
# Repeat array
c = np.array([1,2,3], dtype='int32')
d = np.repeat(c, 3)
print(d)

e = np.array([[1,2,3]], dtype='int32')
f = np.repeat(e,3, axis=0)
print(f)
g = np.repeat(e,3, axis=1)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Example 1

In [69]:
# Build a complex array
output = np.zeros((7,7), dtype='int32')
ones = np.ones((5,5), dtype='int32')
output[1:6, 1:6] = ones
zeros = np.zeros((3,3), dtype='int32')
zeros[1,1] = 1

output[2:5, 2:5] = zeros
print(output)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 1 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


## Copy Elements

In [76]:
g = np.copy(a)
arrayInfo(g)


[[ 1  2  3  7  8 10 13]
 [ 4  5  6  1  3  4  5]
 [ 2  5  6  3  5  6  8]]
Array shape - (3, 7)
Array dimensions - 2
Array Size giving total number of elements - 21
Array itemsize - 2
Array Total Size - 42


## Arithematics | Element wise

In [85]:
h = np.array([[1,2,3], [14,12,10]], dtype='float32')
print(h)

# add to each element
h = h + 1
print(h)

# substract from each element
h = h-2
print(h)

# Multiply with each element
h *= 2
print(h)

# divide each element
h /= 10
print(h)

## raise each element to the power of
h = h ** 2
print(h)

# take sin or cos of values
h = np.cos(h)
print(h)

[[ 1.  2.  3.]
 [14. 12. 10.]]
[[ 2.  3.  4.]
 [15. 13. 11.]]
[[ 0.  1.  2.]
 [13. 11.  9.]]
[[ 0.  2.  4.]
 [26. 22. 18.]]
[[0.  0.2 0.4]
 [2.6 2.2 1.8]]
[[0.         0.04       0.16000001]
 [6.7599993  4.84       3.2399998 ]]
[[ 1.          0.9992001   0.98722726]
 [ 0.88846165  0.12726511 -0.99516195]]


## Linear Algebra

In [94]:
i = np.full((3, 4), 4)
j = np.full((4, 2), 5)

# Matrix multiplications
k = np.matmul(i, j)
print(k)

identity = np.identity(4, dtype='int32')
print(identity)


[[80 80]
 [80 80]
 [80 80]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## Statistics

In [101]:
min = np.min(a)
print(min)

max = np.max(a)
print(max)

# Max of each row -> Use 0 for column
maxAxis = np.max(a, axis=1)
print(maxAxis)

# Sum all elements in array
sum = np.sum(a)
print(sum)

# Sum on axis - > Sum of each row
sumAxis = np.sum(a, axis=1)
print(sumAxis)

1
13
[13  6  8]
107
[44 28 35]


## Reorganize | Reshape Arrays

In [110]:
l = np.array([[1,2,3,4], [8,7,6,5]])
l = l.reshape((8,1))
print(l)

l = l.reshape((4,2))
print(l)
# any combination of shape that fits all the values can be done

m = np.array([1,2,3,4])
n = np.array([4,5,6,7])

# vertically stacking arrays
o = np.vstack([n,m]) # stack as given index
print(o)

# Multistacking the same arrays
p = np.vstack([m, n, m, m, n])
print(p)

# Horizontal stacking
q = np.hstack((m, n)) # Could be round or square brackets
print(q)


[[1]
 [2]
 [3]
 [4]
 [8]
 [7]
 [6]
 [5]]
[[1 2]
 [3 4]
 [8 7]
 [6 5]]
[[4 5 6 7]
 [1 2 3 4]]
[[1 2 3 4]
 [4 5 6 7]
 [1 2 3 4]
 [1 2 3 4]
 [4 5 6 7]]
[1 2 3 4 4 5 6 7]


## Boolean Masking

In [114]:
aValueGreaterThan4 = a > 4
print(aValueGreaterThan4)
# Similar for any compare

valuesGreaterThan4 = a[a > 4]
print(valuesGreaterThan4)


[[False False False  True  True  True  True]
 [False  True  True False False False  True]
 [False  True  True False  True  True  True]]
[ 7  8 10 13  5  6  5  5  6  5  6  8]
